# Generated by Django 5.2.13 on 2026-04-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
